Update kubectl-validate.yaml

diff --git a/.github/workflows/kubectl-validate.yaml b/.github/workflows/kubectl-validate.yaml
--- a/.github/workflows/kubectl-validate.yaml
+++ b/.github/workflows/kubectl-validate.yaml
@@ -23,8 +23,9 @@ jobs:
         run: go install sigs.k8s.io/kubectl-validate@latest
         
       - name: Run kubectl-validate
+        shell: bash
         run: kubectl-validate $MANIFESTS_PATH --version 1.23
         
-      - name: Report status
-        if: failure()
-        run: exit 1
+#       - name: Report status
+#         if: failure()
+#         run: exit 1
